config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'events#index'
  resources :events do 
    resources :attendances, only: [:new, :create, :index]
  end

  resources :users

  # --- Routes for static_pages_controller ---
  resources :static_pages
  get 'static_pages/index'
  get 'static_pages/secret'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/explain', to: 'static_pages#explain'

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user, only: [:secret]

  def index
  end

  def team
  end

  def contact
  end

  def secret
  end

  def explain
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #7f53ac; background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
  
    <div class="py-0">

      <!-- Content -->
     <h2 class="card-title h2 my-4 py-2">Contact us !</h2>
     
      
    </div>
  </div>
</div>
<!-- Jumbotron -->

<div class="container py-5 text-center">
  <br>
  <h5 class="mt-5 pt-5">Va falloir attendre un peu mon piffou</h1></br>
  <small>garde espoir...</small>
  <br>
</div>

app/views/static_pages/explain.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #7f53ac; background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
  
    <div class="py-0">

      <!-- Content -->
      <% if user_signed_in? %>
        <h2 class="card-title h2 my-4 py-2">Our site, simply explained, <%= current_user.first_name %> !</h2>
      <% else %>
        <h2 class="card-title h2 my-4 py-2">Our site, simply explained !</h2>
      <% end %>
      
    </div>
  </div>
</div>
<!-- Jumbotron -->

<div class="container py-5 justify-content-center">
  <iframe width="1200" height="600" src='https://dbdiagram.io/embed/5eb9bbf339d18f5553ff0a76'> </iframe>
</div>

app/views/static_pages/index.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #7f53ac; background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
  
    <div class="py-0">

      <!-- Content -->
      <% if user_signed_in? %>
        <h2 class="card-title h2 my-4 py-2">Welcome, <%= current_user.first_name %> !</h2>
      <% else %>
        <h2 class="card-title h2 my-4 py-2">Welcome, dear visitor !</h2>
      <% end %>
      
    </div>
  </div>
</div>
<!-- Jumbotron -->



<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #7f53ac; background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
  
    <div class="py-0">

      <!-- Content -->
      <h2 class="card-title h2 my-4 py-2">Welcome on your secret page, <%= current_user.first_name %>.</h2>
      
    </div>
  </div>
</div>
<!-- Jumbotron -->

<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/static_pages/team.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #7f53ac; background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
  
    <div class="py-0">

      <!-- Content -->
     <h2 class="card-title h2 my-4 py-2">The team !</h2>
     
      
    </div>
  </div>
</div>
<!-- Jumbotron -->

<div class="container py-5 text-center">
      <br>
      <h1 class="mt-5 pt-5">Nicolas HODEE</h1></br>
      <small>il est devenu un no life depuis...</small>
      <br>
    </div>