config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'events#index'
  resources :events do 
    resources :attendances, only: [:new, :create, :index]
  end

  resources :users

  # --- Routes for static_pages_controller ---
  resources :static_pages
  get 'static_pages/index'
  get 'static_pages/secret'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/explain', to: 'static_pages#explain'

  
end

app/models/event.rb
class Event < ApplicationRecord

    # un event a plusieurs participants, a travers attendances
    has_many :attendances
    has_many :users, through: :attendances

    belongs_to :admin, class_name: "User"

    # checke la presence et renvoie un message si absent ou incorrect
    validates :start_date, presence: true
    validate :start_must_be_future

    validates :duration, presence: true

    validates :location, presence: true
    validates :title, presence: true, length: { in: 5..140 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 50 }


    def start_must_be_future
        return unless start_date 
        errors.add(:start_date, "ne doit pas être passée") unless start_date > Time.now
    end

    def end_date
        start_date + (duration * 60)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # permet de limiter la view aux utilisateurs connectes
  before_action :authenticate_user, only: [:new, :edit]

  #definir une nouvelle instance de la classe event
  def new
    @event = Event.new
  end

  def event_params
    params.require(:event).permit(:title, :description, :start_date, :duration, :location, :price)
  end

  #creer un event a partir des params
  def create
    @event = Event.new(event_params.merge({admin: current_user}))  
    #si les validates du model event sont ok, on save
    if @event.save
      flash[:success] = "Event successfully created"
      redirect_to root_path
    #sinon on affiche une erreur et on redirige sur la page de creation d'event
    else
      flash[:danger] = "Invalid input #{@event.errors.full_messages}"
      render 'new'
    end
  end

  def show
    #affiche tous les events
    @event = Event.find(params[:id])
    #on prevoie d'afficher le nom complet de l'auteur dans la page show
  end

  #creer un array avec les events a venir
  def index
    @events = []
    Event.all.each do |event|
      if event.start_date >= Time.now.strftime("%Y-%m-%d")
        @events << event
      end
    end
  end

  # pour editer un event
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "You successfully edited the event."
      render 'show'
    else
      render 'edit'
    end
  end


  # pour supprimer un event
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:danger] = 'Event deleted'
    redirect_to root_path
  end

  #a partir de la on definit la fonction qui bloque l'acces aux pages secures
  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Not logged in."
      redirect_to root_path
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #63d471; background-image: linear-gradient(315deg, #63d471 0%, #233329 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
    <div class="py-0">
      <!-- Content -->
      <% if signed_in? %>
        <h2 class="card-title h2 my-4 py-2">Amend your event, <%= current_user.first_name %></h2>
      <% else %>
        <h2 class="card-title h2 my-4 py-2">Amend your event, anonymous</h2>
      <% end %>
    </div>
  </div>
</div>
<!-- Jumbotron -->

<% flash.each do |type, msg| %>
  <div class="<%= flash_class(type) %> mt-1 py-1"><%= msg %></div>
<% end %>

<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
        <%= form_for @event do |f| %>
          <div class="form-group">
              <%= f.label :start_date, "Date" %><br />
              <%= f.date_field :start_date, class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :duration, "Duration" %><br />
              <%= f.text_field :duration, autocomplete: "duration", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :title, "Title" %><br />
              <%= f.text_field :title, autocomplete: "title", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :description, "Description" %><br />
              <%= f.text_area :description, autocomplete: "description", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :price, "Price" %><br />
              <%= f.text_field :price, autocomplete: "price", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :location, "Location" %><br />
              <%= f.text_field :location, autocomplete: "location", class: "form-control" %>
          </div>

          <%= submit_tag "Modify event", class: "btn btn-lg btn-primary" %>
        <% end %>

    </div>
  </div>
</div>

app/views/events/index.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #7f53ac; background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
  
    <div class="py-0">

      <!-- Content -->
      <% if user_signed_in? %>
        <h2 class="card-title h2 my-4 py-2">Welcome, <%= current_user.first_name %> !</h2>
      <% else %>
        <h2 class="card-title h2 my-4 py-2">Welcome, dear visitor !</h2>
      <% end %>
      
    </div>
  </div>
</div>
<!-- Jumbotron -->

<% flash.each do |type, msg| %>
  <div class="<%= flash_class(type) %>"><%= msg %></div>
<% end %>

<div class="row justify-content-center m-4">
  <%= link_to "Add an event",  new_event_path , {class: 'btn btn-secondary btn-lg'} %>
</div>

<div class="container">
    <div class="row justify-content-center">
      <div class="card-deck">
        <% Event.all.reverse.each do |event| %>
          
            <!-- Card de boostrap -->
            <div class="card" >
                <div class="card-header">
                    <p><i class=""></i><%= event.start_date %></p>
                </div>

                <!-- Card content -->
                <div class="card-body">
                    <!-- Title -->
                    <h4 class="card-title"><%= event.title %></h4>
                    <!-- Button -->
                    <%= link_to "View details", event_path(event.id), class: "btn btn-primary" %>
                </div>
                <!-- Card footer -->
                <div class="card-footer text-muted text-center">
                    <p>
                        Location : <%= event.location %><br/>
                        Price : <%= event.price %>€
                    </p>
                </div>
            </div>
            <!-- Card -->
        <% end %>
      </div>
    </div>
</div>

app/views/events/new.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #63d471; background-image: linear-gradient(315deg, #63d471 0%, #233329 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
    <div class="py-0">
      <!-- Content -->
      <h2 class="card-title h2 my-4 py-2">Create a new event</h2>
    </div>
  </div>
</div>
<!-- Jumbotron -->

<% flash.each do |type, msg| %>
  <div class="<%= flash_class(type) %> mt-1 py-1"><%= msg %></div>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
        <%= form_for @event do |f| %>
          <div class="form-group">
              <%= f.label :start_date, "Date" %><br />
              <%= f.date_field :start_date, class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :duration, "Duration" %><br />
              <%= f.text_field :duration, autocomplete: "duration", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :title, "Title" %><br />
              <%= f.text_field :title, autocomplete: "title", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :description, "Description" %><br />
              <%= f.text_area :description, autocomplete: "description", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :price, "Price" %><br />
              <%= f.text_field :price, autocomplete: "price", class: "form-control" %>
          </div>

          <div class="form-group">
              <%= f.label :location, "Location" %><br />
              <%= f.text_field :location, autocomplete: "location", class: "form-control" %>
          </div>

          <%= submit_tag "Create event", class: "btn btn-info btn-sm" %>
        <% end %>

    </div>
  </div>
</div>

app/views/events/show.html.erb
<!-- Jumbotron -->
<div class="card card-image rounded-0" style="background-color: #63d471; background-image: linear-gradient(315deg, #63d471 0%, #233329 74%);">
  <div class="text-white text-center rgba-stylish-strong py-0 px-4">
    <div class="py-0">
      <!-- Content -->
      <h2 class="card-title h2 my-4 py-2">Event : <%= @event.title %></h2>
    </div>
  </div>
</div>
<!-- Jumbotron -->

<% if @event.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<!-- CONTENU -->
<div class="container">
  <div class="card mb-5 mt-5 mx-3">
    <div class="card-body">
      <p class="mb-3"><span class="font-weight-bold">Description :</span> <%= @event.description %></p><br/>
      <p class="mb-3"><span class="font-weight-bold">Creator email :</span> <%= @event.admin.email %> </p>
      <p class="mb-3"><span class="font-weight-bold">Creator name :</span> <%= @event.admin.first_name %> <%= @event.admin.last_name %> </p>

      <p class="card-text">
      <p class="text-muted">Price : <%= @event.price %>€</p> 
      <p class="text-muted"> Location : <%= @event.location %></p> 
      <p class="text-muted"> Attendees: <%= @event.users.count %> members are going to this event.</p>
      </p>

      <!-- bloc pour afficher les boutons selon l'utilisateur connecte -->
      <% if signed_in? %>
        <% if current_user == @event.admin %>
          <%= link_to "Manage my event", event_attendances_path(@event), class: 'btn btn-info mt-1 ml-1' %>
        <% end %>
        <% if current_user.id == @event.admin.id %>
          <%= link_to "Edit event", edit_event_path(@event.id), :type => "button",  :class => 'btn btn-info mt-1 ml-1' %>
          <%= link_to "Delete event", event_path(@event.id), :type => "button", :method => :delete, :class => 'btn btn-danger mt-1 ml-1' %>
        <% end %>
        <% if Attendance.where(event: @event,user: current_user).empty? && current_user != @event.admin %>
          <%= link_to "Join event", new_event_attendance_path(@event), :type => "button",  :class => 'btn btn-success mt-1 ml-1' %>
        <% end %>
      <% else %>
        <small style="color:green;" class="">You need to be logged in to join this event</small>
      <% end %>

    </div>
  </div>
</div>